CREATE TABLE Students (
    SID INT PRIMARY KEY,
    LAST_NAME VARCHAR(255),
    FIRST_NAME VARCHAR(255),
    Level INT,
    ADDRESS VARCHAR(255),
    FEE DECIMAL(10, 2)
);
INSERT INTO Students (SID, LAST_NAME, FIRST_NAME, Level, ADDRESS, FEE)
VALUES (1, 'Rose', 'Mary', 400, 'Buea', 200000.00);

INSERT INTO Students (SID, LAST_NAME, FIRST_NAME, Level, ADDRESS, FEE)
VALUES (2, 'John', 'Doe', 300, 'Kumba', 150000.00);
INSERT INTO Students (SID, LAST_NAME, FIRST_NAME, Level, ADDRESS, FEE)
VALUES (3, 'Kate', 'Chloe', 400, 'Kumba', 200000.00);

INSERT INTO Students (SID, LAST_NAME, FIRST_NAME, Level, ADDRESS, FEE)
VALUES (4, 'Ebot', 'Hans', 200, 'Buea', 650000.00);

INSERT INTO Students (SID, LAST_NAME, FIRST_NAME, Level, ADDRESS, FEE)
VALUES (5, 'Mary', 'Jane', 600, 'Limbe', 450000.00);

INSERT INTO Students (SID, LAST_NAME, FIRST_NAME, Level, ADDRESS, FEE)
VALUES (6, 'Clara', 'Tats', 300, 'Tiko', 450000.00);

INSERT INTO Students (SID, LAST_NAME, FIRST_NAME, Level, ADDRESS, FEE)
VALUES (7, 'Josh', 'Wils', 300, 'Douala', 1000000.00);